name: Linter

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    linter:
        strategy:
            matrix:
                php:
                    - 8.1

        name: Linter ${{ matrix.php }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: pdo_sqlite, pdo_mysql, pdo_pgsql
                    coverage: none

            -   run: composer install --no-progress
            -   run: vendor/bin/parallel-lint src tests -e php,phpt
