name: Code Tests

on:
    pull_request: null

jobs:
    tests:
        strategy:
            matrix:
                php:
                    - 8.1

        name: Test ${{ matrix.php }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: pdo_sqlite, pdo_mysql, pdo_pgsql
                    coverage: none

            -   run: composer install --no-progress
            -   run: vendor/bin/phpunit
